/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import static com.sun.java.accessibility.util.SwingEventMonitor.addListSelectionListener;
import javax.swing.JOptionPane;
import java.sql.Connection;
import dao.ConnectionProvider;
import java.awt.HeadlessException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JCheckBox;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author v1p3r
 */
public class AddOrder extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddOrder.class.getName());
    private String username = "";
     private DefaultTableModel stavkeModel;
    /**
     * Creates new form AddOrder
     */
    public AddOrder() {
        initComponents();
        postaviComboboxDobavljace();
        postaviSelektovanjeLijeka();
        setLocationRelativeTo(null);
        postaviModelStavki();
    }
    
    public AddOrder(String tempName){
        username = tempName;
        initComponents();
        postaviComboboxDobavljace();
        postaviModelStavki();
        postaviSelektovanjeLijeka();
        setLocationRelativeTo(null);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLijekovi = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtOdabrani = new javax.swing.JTextField();
        txtCijena = new javax.swing.JTextField();
        txtKolicina = new javax.swing.JTextField();
        btnDialogDodaj = new javax.swing.JButton();
        btnDialogOdustani = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cmbDobavljac = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDatum = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnSacuvajNarudzbu = new javax.swing.JButton();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel6.setText("Dodaj stavku");
        jDialog1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));
        jDialog1.getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 789, -1));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel10.setText("Pretraga");
        jDialog1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));
        jDialog1.getContentPane().add(txtPretraga, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 293, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnSearch.setText("Pretraži");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        jDialog1.getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        txtLijekovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "ATC", "Naziv lijeka", "Proizvodjac", "Cijena"
            }
        ));
        jScrollPane3.setViewportView(txtLijekovi);

        jDialog1.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 112, 550, 166));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel7.setText("Odabrani lijek:");
        jDialog1.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 311, -1, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel8.setText("Nabavna cijena:");
        jDialog1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 351, -1, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel9.setText("Količina:");
        jDialog1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 390, -1, -1));

        txtOdabrani.setEnabled(false);
        txtOdabrani.setFocusCycleRoot(true);
        jDialog1.getContentPane().add(txtOdabrani, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 310, 300, -1));

        txtCijena.setEnabled(false);
        jDialog1.getContentPane().add(txtCijena, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 350, 300, -1));

        txtKolicina.setEnabled(false);
        jDialog1.getContentPane().add(txtKolicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 300, -1));

        btnDialogDodaj.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnDialogDodaj.setText("Dodaj stavku");
        btnDialogDodaj.addActionListener(this::btnDialogDodajActionPerformed);
        jDialog1.getContentPane().add(btnDialogDodaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        btnDialogOdustani.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnDialogOdustani.setText("Odustani");
        btnDialogOdustani.addActionListener(this::btnDialogOdustaniActionPerformed);
        jDialog1.getContentPane().add(btnDialogOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 120, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Naruči lijekove");
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        jLabel1.setText("Dodaj narudžbu");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("Dobavljač");

        cmbDobavljac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setText("Rok isporuke");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Napomena");

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane1.setViewportView(txtNapomena);

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavke);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setText("Stavke narudžbe");

        btnDodajStavku.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(this::btnDodajStavkuActionPerformed);

        btnObrisiStavku.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnObrisiStavku.setText("Obrisi stavku");
        btnObrisiStavku.addActionListener(this::btnObrisiStavkuActionPerformed);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnClose.addActionListener(this::btnCloseActionPerformed);

        btnSacuvajNarudzbu.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnSacuvajNarudzbu.setText("Sačuvaj narudžbu");
        btnSacuvajNarudzbu.addActionListener(this::btnSacuvajNarudzbuActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(499, 499, 499)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDobavljac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))))
                .addContainerGap(472, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 466, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(570, 570, 570))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSacuvajNarudzbu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDodajStavku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnObrisiStavku))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(358, 358, 358))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDobavljac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajStavku)
                    .addComponent(btnObrisiStavku)
                    .addComponent(btnSacuvajNarudzbu))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void postaviSelektovanjeLijeka() {
        txtLijekovi.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int row = txtLijekovi.getSelectedRow();
                if (row != -1) {
                    txtOdabrani.setText(txtLijekovi.getValueAt(row, 2).toString());

                    // Sigurnosna provjera da cijena nije null
                    Object cijenaObj = txtLijekovi.getValueAt(row, 4);
                    txtCijena.setText(cijenaObj != null ? cijenaObj.toString() : "0.00 KM");

                    txtKolicina.setEnabled(true);
                    btnDialogDodaj.setEnabled(true);
                } else {
                    txtOdabrani.setText("");
                    txtCijena.setText("");
                    txtKolicina.setEnabled(false);
                    btnDialogDodaj.setEnabled(false);
                }
            }
        });
    }

    
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        //close button
        setVisible(false);
        new OrderMedicine(username).setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(true);
        jDialog1.setSize(900,600);
        jDialog1.setLocationRelativeTo(this);  
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String search = txtPretraga.getText().trim();
        if (search.isEmpty()) {
            ucitajSveLijekove();
            return;
        }

        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement(
                "SELECT id, atc_sifra, naziv, proizvodjac, cijena " +
                "FROM lijek WHERE naziv LIKE ? OR atc_sifra LIKE ? " +
                "ORDER BY naziv LIMIT 100"
            );
            String like = "%" + search + "%";
            ps.setString(1, like);
            ps.setString(2, like);

            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) txtLijekovi.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("atc_sifra"),
                    rs.getString("naziv"),
                    rs.getString("proizvodjac"),
                    String.format("%.2f", rs.getDouble("cijena"))
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(jDialog1, e);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSacuvajNarudzbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajNarudzbuActionPerformed
        // TODO add your handling code here:
        if (cmbDobavljac.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Odaberite dobavljača!");
            return;
        }

        if (stavkeModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Dodajte barem jednu stavku!");
            return;
        }

        Connection con = null;
        try {
            con = ConnectionProvider.getCon();
            con.setAutoCommit(false);

            // 1. Spremi zaglavlje narudžbe
            PreparedStatement psZaglavlje = con.prepareStatement(
                "INSERT INTO narudzbe (dobavljac_id, datum_kreiranja, rok, status, napomena, ukupno) " +
                "VALUES (?, NOW(), ?, 'Kreirana', ?, ?)",
                Statement.RETURN_GENERATED_KEYS
            );

            // Dobavljač – pretpostavljam da si u comboboxu stavio samo naziv, treba ID
            // Ako nemaš ID u comboboxu, moraš promijeniti postaviComboboxDobavljace da koristi ComboItem
            // Za sada ćemo koristiti naziv – bolje je imati ID
            String dobavljacNaziv = cmbDobavljac.getSelectedItem().toString();
            // Pronađi ID po nazivu (nije idealno, ali radi za test)
            int dobavljacId = pronadjiDobavljacIdPoNazivu(dobavljacNaziv);

            psZaglavlje.setInt(1, dobavljacId);
            psZaglavlje.setDate(2, txtDatum.getDate() != null ? new java.sql.Date(txtDatum.getDate().getTime()) : null);
            psZaglavlje.setString(3, txtNapomena.getText().trim());

            double ukupnoNarudzbe = izracunajUkupnoNarudzbe();
            psZaglavlje.setDouble(4, ukupnoNarudzbe);
            psZaglavlje.executeUpdate();

            ResultSet rs = psZaglavlje.getGeneratedKeys();
            int narudzbaId = -1;
            if (rs.next()) {
                narudzbaId = rs.getInt(1);
            }

            // 2. Spremi sve stavke
            PreparedStatement psStavka = con.prepareStatement(
                "INSERT INTO narudzba_stavke (narudzba_id, lijek_id, kolicina_narucena, nabavna_cijena) " +
                "VALUES (?, ?, ?, ?)"
            );

            for (int i = 0; i < stavkeModel.getRowCount(); i++) {
                String nazivLijeka = stavkeModel.getValueAt(i, 0).toString();
                int kolicina = Integer.parseInt(stavkeModel.getValueAt(i, 1).toString());
                double cijena = Double.parseDouble(
                    stavkeModel.getValueAt(i, 2).toString().replace(" KM", "").replace(",", ".")
                );

                // Pronađi lijek_id po nazivu (nije idealno, bolje čuvati ID u modelu)
                int lijekId = pronadjiLijekIdPoNazivu(nazivLijeka);

                psStavka.setInt(1, narudzbaId);
                psStavka.setInt(2, lijekId);
                psStavka.setInt(3, kolicina);
                psStavka.setDouble(4, cijena);
                psStavka.executeUpdate();
            }

            con.commit();
            JOptionPane.showMessageDialog(this, "Narudžba uspješno sačuvana!");

            // Očisti formu ili zatvori
            dispose();
            new OrderMedicine(username).setVisible(true);

        } catch (Exception ex) {
            if (con != null) {
                try { con.rollback(); } catch (SQLException ignored) {}
            }
            JOptionPane.showMessageDialog(this, "Greška pri spremanju narudžbe:\n" + ex.getMessage());
            ex.printStackTrace();
        } finally {
            if (con != null) {
                try { con.setAutoCommit(true); con.close(); } catch (Exception ignored) {}
            }
        }
    }//GEN-LAST:event_btnSacuvajNarudzbuActionPerformed

    private void btnDialogDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogDodajActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Provjeri da li je količina validna
            String kolicinaStr = txtKolicina.getText().trim();
            if (kolicinaStr.isEmpty()) {
                JOptionPane.showMessageDialog(jDialog1, "Unesite količinu!");
                return;
            }

            int kolicina = Integer.parseInt(kolicinaStr);
            if (kolicina <= 0) {
                JOptionPane.showMessageDialog(jDialog1, "Količina mora biti veća od 0!");
                return;
            }

            // 2. Uzmi cijenu (iz tabele ili polja)
            String cijenaStr = txtCijena.getText().replace(" KM", "").replace(",", ".");
            double cijena = Double.parseDouble(cijenaStr);

            double ukupno = kolicina * cijena;

            // 3. Dodaj red u glavnu tabelu stavki (tblStavke)
            stavkeModel.addRow(new Object[] {
                txtOdabrani.getText(),                  // Naziv lijeka
                kolicina,                               // Količina
                String.format("%.2f KM", cijena),       // Nabavna cijena
                String.format("%.2f KM", ukupno),       // Ukupno za stavku
                "X"                                     // Dugme za brisanje
            });

            // 4. Očisti polja u dialogu (opcionalno)
            txtOdabrani.setText("");
            txtCijena.setText("");
            txtKolicina.setText("");
            txtKolicina.setEnabled(false);
            btnDialogDodaj.setEnabled(false);

            // 5. Zatvori dialog nakon dodavanja
            jDialog1.dispose();

            // 6. Opcionalno: ažuriraj ukupnu sumu narudžbe
            azurirajUkupnoNarudzbe();

        } 
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(jDialog1, "Količina ili cijena nisu ispravni brojevi!");
        } 
        catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(jDialog1, "Greška: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_btnDialogDodajActionPerformed

    private void btnDialogOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogOdustaniActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
    }//GEN-LAST:event_btnDialogOdustaniActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblStavke.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali stavku za brisanje!");
            return;
        }

        stavkeModel.removeRow(selectedRow);
        azurirajUkupnoNarudzbe();
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed
    
    private int pronadjiDobavljacIdPoNazivu(String naziv) throws SQLException {
        Connection con = ConnectionProvider.getCon();
        PreparedStatement ps = con.prepareStatement("SELECT id FROM dobavljaci WHERE naziv = ?");
        ps.setString(1, naziv);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) return rs.getInt("id");
        throw new SQLException("Dobavljač nije pronađen: " + naziv);
    }

    private int pronadjiLijekIdPoNazivu(String naziv) throws SQLException {
        Connection con = ConnectionProvider.getCon();
        PreparedStatement ps = con.prepareStatement("SELECT id FROM lijek WHERE naziv = ?");
        ps.setString(1, naziv);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) return rs.getInt("id");
        throw new SQLException("Lijek nije pronađen: " + naziv);
    }

    private double izracunajUkupnoNarudzbe() {
        double suma = 0;
        for (int i = 0; i < stavkeModel.getRowCount(); i++) {
            String ukupnoStr = stavkeModel.getValueAt(i, 3).toString()
                    .replace(" KM", "")
                    .replace(",", ".");
            try {
                suma += Double.parseDouble(ukupnoStr);
            } catch (Exception ignored) {}
        }
        return suma;
    }
    
    private void ucitajSveLijekove() {
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();

            // Možeš ograničiti broj redova da ne učitava 5000+ lijekova odjednom
            // Ako želiš sve → samo izbriši LIMIT
            String query = """
                SELECT 
                    id, 
                    atc_sifra, 
                    naziv, 
                    proizvodjac, 
                    cijena
                FROM lijek 
                ORDER BY naziv ASC
                LIMIT 300
            """;

            ResultSet rs = st.executeQuery(query);

            // Očisti staro prije punjenja
            DefaultTableModel model = (DefaultTableModel) txtLijekovi.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getInt("id"),
                    rs.getString("atc_sifra") != null ? rs.getString("atc_sifra") : "",
                    rs.getString("naziv"),
                    rs.getString("proizvodjac") != null ? rs.getString("proizvodjac") : "",
                    String.format("%.2f KM", rs.getDouble("cijena"))
                });
            }

            // Opcionalno: ako nema rezultata
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, 
                    "Nema lijekova u bazi ili nisu učitani.", 
                    "Upozorenje", 
                    JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                "Greška pri učitavanju lijekova:\n" + ex.getMessage(), 
                "Greška", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void postaviComboboxDobavljace() {
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT id, naziv FROM dobavljaci ORDER BY naziv");

            cmbDobavljac.removeAllItems();
            while (rs.next()) {
                cmbDobavljac.addItem(rs.getString("naziv"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    private void postaviModelStavki() {
        stavkeModel = new DefaultTableModel(
            new String[]{"Lijek", "Količina", "Nab. cijena", "Ukupno", " "},  // zadnja kolona za dugme
            0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return col == 1; // samo količina se može mijenjati direktno u tabeli
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 1) return Integer.class;
                if (columnIndex == 2 || columnIndex == 3) return String.class; // cijene kao string zbog " KM"
                return Object.class;
            }
        };

        tblStavke.setModel(stavkeModel);

        // Postavi renderer i editor SAMO na zadnju kolonu (index 4)
        int kolonaDugme = 4;
        tblStavke.getColumnModel().getColumn(kolonaDugme).setCellRenderer(new ButtonRenderer());
        tblStavke.getColumnModel().getColumn(kolonaDugme).setCellEditor(new ButtonEditor(new JCheckBox()));

        // Sužavanje kolone sa dugmetom
        tblStavke.getColumnModel().getColumn(kolonaDugme).setPreferredWidth(40);
        tblStavke.getColumnModel().getColumn(kolonaDugme).setMaxWidth(60);
        tblStavke.getColumnModel().getColumn(kolonaDugme).setResizable(false);

        // Opcionalno: centriraj tekst u kolonama cijena i količine
        tblStavke.getColumnModel().getColumn(1).setCellRenderer(new DefaultTableCellRenderer() {
            { setHorizontalAlignment(SwingConstants.CENTER); }
        });
    }
    
    private void azurirajUkupnoNarudzbe() {
        double suma = 0;
        for (int i = 0; i < stavkeModel.getRowCount(); i++) {
            String ukupnoStr = stavkeModel.getValueAt(i, 3).toString()
                    .replace(" KM", "")
                    .replace(",", ".");
            try {
                suma += Double.parseDouble(ukupnoStr);
            } catch (NumberFormatException ignored) {}
        }
        // npr. lblUkupno.setText(String.format("Ukupno: %.2f KM", suma));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddOrder().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDialogDodaj;
    private javax.swing.JButton btnDialogOdustani;
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnSacuvajNarudzbu;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbDobavljac;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtCijena;
    private com.toedter.calendar.JDateChooser txtDatum;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTable txtLijekovi;
    private javax.swing.JTextArea txtNapomena;
    private javax.swing.JTextField txtOdabrani;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables
}
