import javax.swing.JOptionPane;
import java.sql.Connection;
import dao.ConnectionProvider;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author v1p3r
 */
public class OrderMedicine extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderMedicine.class.getName());
    private String username = "";
    /**
     * Creates new form OrderMedicine
     */
    public OrderMedicine() {
        initComponents();
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
    }
    
    public OrderMedicine(String tempName){
        initComponents();
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        username = tempName;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Narudzbe");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1360, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        jLabel1.setText("Narudžbe");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButton2.setText("Dodaj");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButton3.setText("Detalji");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButton4.setText("Obriši");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Datum kreiranja", "Dobavljač", "Status", "Ukupno KM", "Stavki", "Napomena"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(493, 493, 493)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PharmacistDashboard(username).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
      ucitajNarudzbe();
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       setVisible(false);
       new AddOrder(username).setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali nijednu narudžbu!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int narudzbaId = (Integer) jTable1.getValueAt(selectedRow, 0);

        // Otvori novi prozor sa detaljima narudžbe
        OrderDetails detaljiForma = new OrderDetails(username, narudzbaId);
        detaljiForma.setVisible(true);

        // Kad se detalji zatvore → osvježi listu
        detaljiForma.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                ucitajNarudzbe();
            }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali nijednu narudžbu!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int narudzbaId = (Integer) jTable1.getValueAt(selectedRow, 0);
        String status = (String) jTable1.getValueAt(selectedRow, 3);

        // Dozvoli brisanje samo ako je Kreirana ili Otkazana
        if (!"Kreirana".equals(status) && !"Otkazana".equals(status)) {
            JOptionPane.showMessageDialog(this, 
                "Možete obrisati samo narudžbe sa statusom 'Kreirana' ili 'Otkazana'!", 
                "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int potvrda = JOptionPane.showConfirmDialog(this,
            "Da li zaista želite obrisati narudžbu #" + narudzbaId + "?\nOvo će obrisati i sve stavke!\nAkcija se ne može poništiti.",
            "Potvrda brisanja",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (potvrda != JOptionPane.YES_OPTION) return;

        try {
            Connection con = ConnectionProvider.getCon();
            con.setAutoCommit(false);

            // Briše stavke (ako postoji foreign key sa ON DELETE CASCADE, ovo nije potrebno)
            PreparedStatement psStavke = con.prepareStatement("DELETE FROM narudzba_stavke WHERE narudzba_id = ?");
            psStavke.setInt(1, narudzbaId);
            psStavke.executeUpdate();

            // Briše zaglavlje narudžbe
            PreparedStatement psNarudzba = con.prepareStatement("DELETE FROM narudzbe WHERE id = ?");
            psNarudzba.setInt(1, narudzbaId);
            psNarudzba.executeUpdate();

            con.commit();

            JOptionPane.showMessageDialog(this, "Narudžba #" + narudzbaId + " uspješno obrisana!");
            ucitajNarudzbe();  // osvježi tabelu

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Greška pri brisanju narudžbe:\n" + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    
private void ucitajNarudzbe() {
    try {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        Connection con = ConnectionProvider.getCon();
        Statement st = con.createStatement();

        String query = """
            SELECT 
                n.id,
                n.datum_kreiranja,
                d.naziv AS dobavljac,
                n.status,
                n.ukupno,
                COUNT(ns.id) AS broj_stavki,
                n.napomena
            FROM narudzbe n
            LEFT JOIN dobavljaci d ON n.dobavljac_id = d.id
            LEFT JOIN narudzba_stavke ns ON n.id = ns.narudzba_id
            GROUP BY n.id, n.datum_kreiranja, d.naziv, n.status, n.ukupno, n.napomena
            ORDER BY n.datum_kreiranja DESC
        """;

        ResultSet rs = st.executeQuery(query);

        while (rs.next()) {
            String ukupnoStr = rs.getBigDecimal("ukupno") != null 
                ? String.format("%.2f KM", rs.getBigDecimal("ukupno")) 
                : "0.00 KM";

            model.addRow(new Object[] {
                rs.getInt("id"),
                rs.getTimestamp("datum_kreiranja"),
                rs.getString("dobavljac"),
                rs.getString("status"),
                ukupnoStr,
                rs.getInt("broj_stavki"),
                rs.getString("napomena") != null ? rs.getString("napomena") : ""
            });
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Greška pri učitavanju narudžbi:\n" + e.getMessage());
        e.printStackTrace();
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OrderMedicine().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
