/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import dao.ConnectionProvider;
import java.awt.HeadlessException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JCheckBox;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author v1p3r
 */
public class OrderDetails extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderDetails.class.getName());
    private String username = "";
    private int narudzbaID = -1;
    /**
     * Creates new form OrderDetails
     */
    public OrderDetails() {
        initComponents();
        ucitajDetaljeNarudzbe();
        ucitajStavke();
    }
    public OrderDetails(String tempName, int tempID){
        initComponents();
        username = tempName;
        narudzbaID = tempID;
        setLocationRelativeTo(null);
        ucitajDetaljeNarudzbe();
        ucitajStavke();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnZatvori = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDobavljac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRokIsporuke = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUkupnaCijena = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLijekovi = new javax.swing.JTable();
        txtStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Narudzba detalji");
        setUndecorated(true);

        btnZatvori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnZatvori.addActionListener(this::btnZatvoriActionPerformed);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        jLabel1.setText("Narudžba detalji");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabel2.setText("ID");

        txtID.setEnabled(false);

        jLabel3.setText("Datum kreiranja");

        txtDatum.setEnabled(false);

        jLabel4.setText("Dobavljač");

        txtDobavljac.setEnabled(false);

        jLabel5.setText("Rok isporuke");

        txtRokIsporuke.setEnabled(false);

        jLabel6.setText("Status ");

        jLabel7.setText("Ukupno");

        txtUkupnaCijena.setEnabled(false);

        jLabel8.setText("Napomena");

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        txtNapomena.setEnabled(false);
        jScrollPane1.setViewportView(txtNapomena);

        txtLijekovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ATC", "Naziv", "Naručeno", "Nabavna cijena", "Ukupno"
            }
        ));
        jScrollPane2.setViewportView(txtLijekovi);

        txtStatus.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(95, 95, 95)
                            .addComponent(txtID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUkupnaCijena)
                            .addComponent(txtRokIsporuke)
                            .addComponent(txtDobavljac)
                            .addComponent(txtDatum)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(txtStatus))))
                .addContainerGap(537, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnZatvori)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(338, 338, 338))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnZatvori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDobavljac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRokIsporuke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtUkupnaCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new OrderMedicine(username).setVisible(true);
    }//GEN-LAST:event_btnZatvoriActionPerformed
    
    private void ucitajDetaljeNarudzbe() {
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement(
                "SELECT n.id, n.datum_kreiranja, d.naziv AS dobavljac, " +
                "n.rok, n.status, n.ukupno, n.napomena " +
                "FROM narudzbe n LEFT JOIN dobavljaci d ON n.dobavljac_id = d.id " +
                "WHERE n.id = ?"
            );
            ps.setInt(1, narudzbaID);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                txtID.setText(String.valueOf(rs.getInt("id")));
                txtDatum.setText(rs.getTimestamp("datum_kreiranja") != null ? rs.getTimestamp("datum_kreiranja").toString() : "");
                txtDobavljac.setText(rs.getString("dobavljac") != null ? rs.getString("dobavljac") : "");
                txtRokIsporuke.setText(rs.getDate("rok") != null ? rs.getDate("rok").toString() : "Nije definiran");
                txtStatus.setText(rs.getString("status"));
                txtUkupnaCijena.setText(String.format("%.2f KM", rs.getDouble("ukupno")));
                txtNapomena.setText(rs.getString("napomena") != null ? rs.getString("napomena") : "");
            } else {
                JOptionPane.showMessageDialog(this, "Narudžba sa ID " + narudzbaID + " nije pronađena!");
                dispose();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju detalja:\n" + ex.getMessage());
            ex.printStackTrace();
        }
    }

    private void ucitajStavke() {
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement(
                "SELECT l.atc_sifra, l.naziv, ns.kolicina_narucena, " +
                "ns.nabavna_cijena, (ns.kolicina_narucena * ns.nabavna_cijena) AS ukupno " +
                "FROM narudzba_stavke ns JOIN lijek l ON ns.lijek_id = l.id " +
                "WHERE ns.narudzba_id = ? ORDER BY ns.id"
            );
            ps.setInt(1, narudzbaID);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = (DefaultTableModel) txtLijekovi.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("atc_sifra") != null ? rs.getString("atc_sifra") : "",
                    rs.getString("naziv"),
                    rs.getInt("kolicina_narucena"),
                    String.format("%.2f KM", rs.getDouble("nabavna_cijena")),
                    String.format("%.2f KM", rs.getDouble("ukupno"))
                });
            }

            // Centriraj kolone (opcionalno)
            DefaultTableCellRenderer center = new DefaultTableCellRenderer();
            center.setHorizontalAlignment(SwingConstants.CENTER);
            txtLijekovi.getColumnModel().getColumn(2).setCellRenderer(center); // Naručeno
            txtLijekovi.getColumnModel().getColumn(3).setCellRenderer(center); // Cijena
            txtLijekovi.getColumnModel().getColumn(4).setCellRenderer(center); // Ukupno

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju stavki:\n" + ex.getMessage());
            ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OrderDetails().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZatvori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtDobavljac;
    private javax.swing.JTextField txtID;
    private javax.swing.JTable txtLijekovi;
    private javax.swing.JTextArea txtNapomena;
    private javax.swing.JTextField txtRokIsporuke;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtUkupnaCijena;
    // End of variables declaration//GEN-END:variables
}
