/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import dao.ConnectionProvider;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.sql.SQLException;
import java.util.Date;
/**
 *
 * @author v1p3r
 */
public class Profile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profile.class.getName());
    private String username = "";
    private String emailpattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    private String phonepattern = "^[0-9]*$";
    /**
     * Creates new form Profile
     * @param tempName
     */
    public Profile(String tempName){
        initComponents();
        username = tempName;
        setLocationRelativeTo(null);

    }
    public Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtIme = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMobilePhone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDatum = new com.toedter.calendar.JDateChooser();
        txtRole = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 768));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        jLabel1.setText("Profil");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 29, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, 1360, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 149, -1, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 149, -1, -1));

        txtEmail.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 150, 300, -1));

        txtIme.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtIme.setText("Ime_Prezime");
        getContentPane().add(txtIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 267, -1, -1));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setText("Datum rođenja");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 334, -1, -1));
        getContentPane().add(txtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 211, 300, -1));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel7.setText("Adresa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 211, -1, -1));
        getContentPane().add(txtMobilePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 269, 300, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel8.setText("Telefon");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 267, -1, -1));
        getContentPane().add(txtDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 334, 300, -1));

        txtRole.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        txtRole.setText("Apotekar");
        getContentPane().add(txtRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 299, -1, -1));

        jButton2.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton2.setText("Sačuvaj");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 391, -1, -1));

        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: //save
        String email = txtEmail.getText();
        String adress = txtAdress.getText();
        String phone = txtMobilePhone.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = txtDatum.getDate();
        String dob = "";
        if(date != null){
            dob = dFormat.format(txtDatum.getDate());
        }
        
        if(email.equals("")){
            JOptionPane.showMessageDialog(null, "Email mora biti unešen!");
        }
        else if(!email.matches(emailpattern)){
            JOptionPane.showMessageDialog(null, "Unešeni email nije ispravan!");
        }
        else if(adress.equals("")){
            JOptionPane.showMessageDialog(null, "Adresa mora biti unešena!");
        }
        else if(phone.equals("")){
            JOptionPane.showMessageDialog(null, "Broj telefona mora biti unešen!");
        }
        else if(!phone.matches(phonepattern) || phone.length() != 10){
            JOptionPane.showMessageDialog(null, "Broj telefona nije ispravan!");
        }
        else if(dob.equals("")){
            JOptionPane.showMessageDialog(null, "Datum rođenja mora biti unešen!");
        }
        else{
            try{
                Connection con = ConnectionProvider.getCon();
                PreparedStatement st = con.prepareStatement("UPDATE `users` SET dob = ?, mobileNumber = ?, email = ?, adress = ? WHERE name = ?");
                st.setString(1, dob);
                st.setString(2, phone);
                st.setString(3, email);
                st.setString(4, adress);
                st.setString(5, txtIme.getText());
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Promjene za korisnika su sačuvane!");
                setVisible(false);
                new AdminDashboard(username).setVisible(true);
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM users WHERE name = '"+username+"' ");
            
            while(rs.next()){
                SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
                String dob = rs.getString("dob");
                Date date;
                try{
                    date = dFormat.parse(dob);
                    txtDatum.setDate(date);

                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);

                }

                txtIme.setText(rs.getString("name"));
                txtRole.setText(rs.getString("userRole"));
                txtEmail.setText(rs.getString("email"));
                txtAdress.setText(rs.getString("adress"));
                txtMobilePhone.setText(rs.getString("mobileNumber"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM users WHERE name = '"+username+"'");
            while(rs.next()){
                if(rs.getString("userRole").equals("Vlasnik")){
                    setVisible(false);
                    new AdminDashboard(username).setVisible(true);
                }
                else{
                    setVisible(false);
                    new PharmacistDashboard(username).setVisible(true);
                }
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Profile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAdress;
    private com.toedter.calendar.JDateChooser txtDatum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtIme;
    private javax.swing.JTextField txtMobilePhone;
    private javax.swing.JLabel txtRole;
    // End of variables declaration//GEN-END:variables
}
