
import javax.swing.JOptionPane;
import java.sql.Connection;
import dao.ConnectionProvider;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author v1p3r
 */
public class UpdateUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateUser.class.getName());
    private String username = "";
    private String emailpattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    private String phonepattern = "^[0-9]*$";
    /**
     * Creates new form UpdateUser
     * @param tempName
     */
    public UpdateUser(String tempName){
        initComponents();
        username = tempName;
        setLocationRelativeTo(null);
    }
    public UpdateUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtRole = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDob = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAdresa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1360, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        jLabel1.setText("Uredi korisnika");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 61, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1319, 29, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 1360, 10));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel2.setText("Ime");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 160, 321, -1));

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton2.setText("Pretraži");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 157, -1, -1));

        txtRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vlasnik", "Farmaceut" }));
        getContentPane().add(txtRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 236, 300, -1));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Datum rođenja");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 296, -1, -1));
        getContentPane().add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 292, 300, -1));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 345, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 344, 300, -1));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setText("Broj telefona");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 400, -1, -1));
        getContentPane().add(txtTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 399, 300, -1));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel7.setText("Adresa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 452, -1, -1));
        getContentPane().add(txtAdresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 451, 300, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton3.setText("Sačuvaj");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, -1, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel8.setText("Uloga");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 237, -1, -1));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 237, 300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new AdminDashboard(username).setVisible(true); //cesto se provjerava ime kroz bazu zato se ova linija ponavlja 3 miliona puta
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: save
        String name = txtName.getText();
        String role = (String) txtRole.getSelectedItem();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = txtDob.getDate();
        String dob = "";
        if(date != null){
            dob = dFormat.format(txtDob.getDate());
        }
        String mobileNum = txtTelefon.getText();
        String email = txtEmail.getText();
        String adress = txtAdresa.getText();
        
        if(mobileNum.equals("")){
            JOptionPane.showMessageDialog(null, "Broj telefona nije unešen!");
        }
        else if(email.equals("")){
            JOptionPane.showMessageDialog(null, "Email nije unešen!");
        }
        else if(!mobileNum.matches(phonepattern) || mobileNum.length() != 10){
            JOptionPane.showMessageDialog(null, "Broj telefona nije ispravan!");
        }
        else if(adress.equals("")){
            JOptionPane.showMessageDialog(null, "Adresa nije unešena!");
        }
        else if(dob.equals("")){
            JOptionPane.showMessageDialog(null, "Datum rođenja nije unešen!");
        }
        else if(!email.matches(emailpattern)){
            JOptionPane.showMessageDialog(null, "Unesešena email adresa nije ispravna!");
        }
        else{
            try{
                Connection con = ConnectionProvider.getCon();
                PreparedStatement st = con.prepareStatement("UPDATE `users` SET dob = ?, userRole = ?, mobileNumber = ?, email = ?, adress = ? WHERE name = ?");
                st.setString(1, dob);
                st.setString(2, role);
                st.setString(3, mobileNum);
                st.setString(4, email);
                st.setString(5, adress);
                st.setString(6, name);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Promjene za korisnika su sačuvane!");
                setVisible(false);
                new AdminDashboard(username).setVisible(true);

            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: search
        int checkUserExist = 0;
        String username = txtName.getText();
        if(username.equals("")){
            JOptionPane.showMessageDialog(null, "Ime nije unešeno!");
        }
        else{
            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
            try{
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM users WHERE name = '"+username+"' ");
                while(rs.next()){
                    txtName.setEditable(false);
                    checkUserExist = 1;
                    txtUsername.setText(rs.getString("name"));
                    txtEmail.setText(rs.getString("email"));
                    txtTelefon.setText(rs.getString("mobileNumber"));
                    txtAdresa.setText(rs.getString("adress"));
                    String dob = rs.getString("dob");
                    if(dob != ""){
                        try{
                            txtDob.setDate(dFormat.parse(dob));
                        }
                        catch(Exception e){
                            JOptionPane.showMessageDialog(null, e);

                        }
                    }
                    if(rs.getString("userRole").equals("Admin")){
                        txtRole.removeAllItems();
                        txtRole.addItem("Vlasnik");
                        txtRole.addItem("Farmaceut");
                    }
                    else{
                        txtRole.removeAllItems();
                        txtRole.addItem("Farmaceut");
                        txtRole.addItem("Vlasnik");
                    }
                    
                  
                }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
            
            if(checkUserExist == 0){
                JOptionPane.showMessageDialog(null, "Ovo ime ne postoji u bazi podataka");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAdresa;
    private com.toedter.calendar.JDateChooser txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JComboBox<String> txtRole;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
